In [4]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

df = pd .read_csv('final.csv')

In [16]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('final.csv')  # make sure the file path is correct

# Loop through each column and print unique values
for column in df.columns:
    print(f"Unique values in column '{column}':")
    print(df[column].unique())
    print("\n" + "-"*50 + "\n")
abs

Unique values in column 'Unnamed: 0':
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.
  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.
  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.
  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.
  98.  99. 100. 101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111.
 112. 113. 114. 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125.
 126. 127. 128. 129. 130. 131. 132. 133. 134. 135. 136. 137. 138. 139.
 140. 141. 142. 143. 144. 145. 146. 147. 148. 149. 150. 151. 152. 153.
 154. 155. 156. 157. 158. 159. 160. 161. 162. 163. 164. 165. 166. 167.
 168. 169. 170. 171. 172. 173. 174. 175. 176. 177. 178. 179. 180. 181.
 182. 183. 184. 185. 186. 187. 188. 189. 190. 191. 192. 193. 194. 195.
 196. 197. 198. 199. 200. 201. 202. 203. 204. 205. 206. 207. 208. 209.
 210. 211. 212. 213. 214. 215. 216. 217. 218. 219. 220. 221. 222. 223.
 224. 225. 226. 227. 228. 229. 230. 231. 232. 233. 234. 235. 236. 237.
 238. 239. 240. 241. 242. 243. 244. 245. 246. 247. 248. 249. 250. 251.
 252. 253. 254. 255. 256. 257. 258. 259. 260. 261. 262. 263. 264. 265.
 266. 267. 268. 269. 270. 271. 272. 273. 274. 275. 276. 277. 278. 279.
 280. 281. 282. 283. 284. 285. 286. 287. 288. 289. 290. 291. 292. 293.
 294. 295. 296. 297. 298. 299. 300. 301. 302. 303. 304. 305. 306. 307.
 308. 309. 310. 311. 312. 313. 314. 315. 316. 317. 318. 319. 320. 321.
 322. 323. 324.  nan]

--------------------------------------------------

Unique values in column 'Zone':
['Northern' 'Western' 'Southern' 'Eastern' 'Central' 'North Eastern'
 'Zone']

--------------------------------------------------

Unique values in column 'State':
['Delhi' 'Maharastra' 'Karnataka' 'Telangana' 'West Bengal' 'Goa'
 'Gujarat' 'Rajasthan' 'Punjab' 'Kerala' 'Maharashtra' 'Madhya Pradesh'
 'Himachal Pradesh' 'Uttarakhand' 'Uttar Pradesh' 'Jammu and Kashmir'
 'Ladakh' 'Odisha' 'Tamil Nadu' 'Andhra Pradesh' 'Sikkim' 'Assam'
 'Arunachal Pradesh' 'Tripura' 'Chhattisgarh' 'Nagaland' 'Puducherry'
 'Andaman and Nicobar Islands' 'Daman and Diu' 'Jharkhand' 'Bihar'
 'Haryana' 'Meghalaya' 'State']

--------------------------------------------------

Unique values in column 'City':
['Delhi' 'Mumbai' 'Lonavala' 'Bangalore' 'Hyderabad' 'Kolkata' 'Goa'
 'Ahmedabad' 'Dwarka' 'Junagadh' 'Bhuj' 'Vadodara' 'Somnath'
 'Rann of Kutch' 'Kevadia' 'Gandhinagar' 'Jaipur' 'Udaipur' 'Jaisalmer'
 'Sawai Madhopur' 'Pushkar' 'Ajmer' 'Jodhpur' 'Chittorgarh' 'Mount Abu'
 'Bikaner' 'Amritsar' 'Chandigarh' 'Alappuzha' 'Munnar' 'Kochi'
 'Thiruvananthapuram' 'Kozhikode' 'Wayanad' 'Thekkady' 'Kumarakom'
 'Varkala' 'Bekal' 'Kovalam' 'Kannur' 'Nelliyampathy' 'Mysore' 'Hampi'
 'Coorg' 'Gokarna' 'Chikmagalur' 'Badami' 'Shivamogga' 'Mangalore'
 'Murudeshwar' 'Bijapur' 'Bandipur' 'Halebidu' 'Pune' 'Aurangabad'
 'Nashik' 'Shirdi' 'Alibaug' 'Ratnagiri' 'Nagpur' 'Kolhapur' 'Tarkarli'
 'Satara' 'Matheran' 'Ajanta' 'Khajuraho' 'Bhopal' 'Indore' 'Gwalior'
 'Ujjain' 'Jabalpur' 'Pachmarhi' 'Kanha' 'Bandhavgarh' 'Orchha' 'Mandu'
 'Bhimbetka' 'Amarkantak' 'Chitrakoot' 'Shimla' 'Manali' 'dalhousie'
 'Dalhousie' 'Spiti Valley' 'Kullu' 'Chamba' 'Kinnaur' 'Kangra' 'Palampur'
 'Mandi' 'Bir Billing' 'McLeod Ganj' 'Manikaran' 'Narkanda' 'Barot'
 'Shoja' 'Kufri' 'Nainital' 'Rishikesh' 'Haridwar' 'Dehradun' 'Mussoorie'
 'Auli' 'Badrinath' 'Almora' 'Ranikhet' 'Jim Corbett' 'Uttarkashi'
 'Chopta' 'Joshimath' 'Agra' 'Varanasi' 'Lucknow' 'Mathura' 'Ayodhya'
 'Vrindavan' 'Allahabad' 'Jhansi' 'Sarnath' 'Fatehpur Sikri' 'Noida'
 'Aligarh' 'Meerut' 'Kanpur' 'Srinagar' 'Leh' 'Pahalgam' 'Jammu'
 'Udhampur' 'Anantnag' 'Nubra Valley' 'Kargil' 'Diskit' 'Kishtwar' 'Hemis'
 'Dras' 'Porbandar' 'Darjeeling' 'Siliguri' 'Sundarbans' 'Digha'
 'Murshidabad' 'Bolpur' 'Hooghly' 'Jalpaiguri' 'Cooch Behar' 'Purulia'
 'Puri' 'Konark' 'Bhubaneswar' 'Rourkela' 'Cuttack' 'Sambalpur' 'Chilika'
 'Berhampur' 'Keonjhar' 'Balasore' 'Kendujhar' 'Chennai' 'Madurai'
 'Rameswaram' 'Kanyakumari' 'Ooty' 'Coimbatore' 'Kodaikanal' 'Thanjavur'
 'Mahabalipuram' 'Yercaud' 'Tirunelveli' 'Chidambaram' 'Vijayawada'
 'Visakhapatnam' 'Srisailam' 'Rajahmundry' 'Anantapur' 'Kurnool'
 'Amravati' 'Guntur' 'Kadapa' 'Puttaparthi' 'Vizianagaram' 'Gangtok'
 'Pelling' 'Namchi' 'Ravangla' 'Guwahati' 'Kaziranga' 'Sivasagar' 'Majuli'
 'Manas' 'Hajo' 'Tawang' 'Agartala' 'Dumboor' 'Unakoti' 'Bastar'
 'Dz√ºkou Valley' 'Puducherry' 'Auroville' 'Port Blair' 'Havelock Island'
 'Neil Island' 'Baratang Island' 'Diu' 'Deoghar' 'Ranchi' 'Bodh Gaya'
 'Patna' 'Gurugram' 'New Delhi' 'Kedarnath' 'Greater Noida' 'Bengaluru'
 'Cherrapunji' 'City']

--------------------------------------------------

Unique values in column 'Name':
['India Gate' "Humayun's Tomb" 'Akshardham Temple' 'Waste to Wonder Park'
 'Jantar Mantar' 'Chandni Chowk' 'Lotus Temple' 'Red Fort'
 'Agrasen ki Baoli' 'Sunder Nursery' 'Garden of Five Senses'
 'Lodhi Garden' 'National Gallery of Modern Art'
 'National Zoological Park ' 'Qutub Minar' 'National Science Centre'
 'Marine Drive' 'Gateway of India'
 'Chhatrapati Shivaji Maharaj Vastu Sangrahalaya'
 'Sanjay Gandhi National Park' 'Siddhivinayak Temple' 'Mahalaxmi Temple'
 'Haji Ali Dargah' 'Chowpatty Beach' 'Essel World' 'Elephanta Caves'
 'Imagicaa' 'Bangalore Palace' 'Lalbagh Botanical Garden' 'Cubbon Park'
 'Vidhana Soudha' 'ISKCON Temple Bangalore' 'Charminar' 'Golconda Fort'
 'Hussain Sagar Lake' 'Ramoji Film City' 'Salar Jung Museum'
 'Qutb Shahi Tombs' 'Birla Mandir' 'Chowmahalla Palace'
 'Nehru Zoological Park' 'Lumbini Park' 'Victoria Memorial'
 'Howrah Bridge' 'Indian Museum' 'Dakshineswar Kali Temple'
 'Kalighat Kali Temple' 'Eden Gardens' 'Alipore Zoological Gardens'
 'Science City Kolkata' 'Belur Math' 'Marble Palace' 'Calangute Beach'
 'Basilica of Bom Jesus' 'Fort Aguada' 'Dudhsagar Falls' 'Anjuna Beach'
 'Chapora Fort' 'Se Cathedral' 'Baga Beach' 'Arambol Beach'
 'Palolem Beach' 'Colva Beach' 'Miramar Beach' 'Aguada Beach'
 'Dr. Salim Ali Bird Santuary' 'Sabarmati Ashram' 'Dwarkadhish Temple'
 'Gir National Park' 'White Desert' 'Laxmi Vilas Palace' 'Somnath Temple'
 'Rann Utsav' 'Statue of Unity' 'Dandi Kutir' 'Sabarmati Riverfront'
 'Manek Chowk' 'Kankaria Lake' 'Science City' 'Hawa Mahal' 'City Palace'
 'Jaisalmer Fort' 'Ranthambore National Park' 'Pushkar Lake'
 'Ajmer Sharif Dargah' 'Mehrangarh Fort' 'Chittorgarh Fort'
 'Dilwara Temples' 'Junagarh Fort' 'Amber Fort' 'Jaigarh Fort'
 'Lake Pichola' 'Golden Temple (Harmandir Sahib)' 'Jallianwala Bagh'
 'Wagah Border' 'Rock Garden' 'Alappuzha Beach' 'Munnar Tea Gardens'
 'Fort Kochi' 'Padmanabhaswamy Temple' 'Kozhikode Beach'
 'Wayanad Wildlife Sanctuary' 'Periyar National Park'
 'Kumarakom Bird Sanctuary' 'Varkala Beach' 'Bekal Fort' 'Kovalam Beach'
 'St. Angelo Fort' 'Seethargundu Viewpoint' 'Kerala Folklore Museum'
 'Wonderla Amusement Park' 'Mysore Palace' 'Hampi Archaeological Ruins'
 'Abbey Falls' 'Om Beach' 'Mullayanagiri' 'Badami Cave Temples'
 'Jog Falls' 'Panambur Beach' 'Murudeshwar Temple' 'Gol Gumbaz'
 'Bandipur National Park' 'Halebidu Hoysaleswara Temple' 'Shaniwar Wada'
 'Ajanta Caves' 'Sula Vineyards' 'Sai Baba Temple' 'Alibaug Beach'
 'Ganapatipule Temple' 'Deekshabhoomi' 'Mahalakshmi Temple' 'Karla Caves'
 'Tarkarli Beach' 'Kaas Plateau' 'Echo Point' 'Ellora Caves'
 'Khajuraho Group of Monuments' 'Sanchi Stupa' 'Rajwada Palace'
 'Gwalior Fort' 'Mahakaleshwar Jyotirlinga' 'Dhuandhar Falls' 'Bee Falls'
 'Kanha National Park' 'Bandhavgarh National Park' 'Orchha Fort'
 'Jahaz Mahal' 'Bhimbetka Rock Shelters' 'Narmada Udgam Temple'
 'Chitrakoot Falls' 'The Ridge' 'Solang Valley' 'Dalai Lama Temple'
 'Khajjiar Lake' 'Key Monastery' 'Great Himalayan National Park'
 'Chamera Lake' 'Sangla Valley' 'Kangra Fort' 'Tea Gardens' 'Prashar Lake'
 'Paragliding Site' 'Triund Trek' 'Manikaran Sahib' 'Hatu Peak'
 'Barot Valley' 'Serolsar Lake' 'Kufri Fun World' 'Naini Lake'
 'Laxman Jhula' 'Har Ki Pauri' "Robber's Cave" 'Kempty Falls'
 'Auli Ski Resort' 'Badrinath Temple' 'Binsar Wildlife Sanctuary'
 'Chaubatia Gardens' 'Jim Corbett National Park' 'Gangotri Temple'
 'Tungnath Temple' 'Valley of Flowers' 'Taj Mahal'
 'Kashi Vishwanath Temple' 'Bara Imambara' 'Krishna Janmabhoomi'
 'Ram Janmabhoomi' 'Banke Bihari Temple' 'Triveni Sangam' 'Jhansi Fort'
 'Dhamek Stupa' 'Buland Darwaza' 'Okhla Bird Sanctuary' 'Aligarh Fort'
 'Augarnath Temple' 'Allen Forest Zoo' 'Dal Lake' 'Pangong Tso'
 'Betaab Valley' 'Vaishno Devi' 'Patnitop Height' 'Amarnath Cave'
 'Thiksey Monastery' 'Nubra Valley' 'Kargil War Memorial'
 'Diskit Monastery' 'Kishtwar National Park' 'Hemis National Park'
 'Dras War Memorial' 'Magnetic Hill' 'Khardung La Pass' 'Prem Mandir'
 'Kirti Mandir' 'Nand Gaon' 'Barsana Mandir' 'Tiger Hill'
 'Jaldapara National Park' 'Sundarbans National Park' 'Digha Beach'
 'Hazarduari Palace' 'Kankalitala Temple' 'Hangseswari Temple'
 'Gorumara National Park' 'Cooch Behar Palace' 'Ayodhya Hills'
 'Jagannath Temple' 'Sun Temple' 'Lingaraj Temple' 'Khandadhar Waterfall'
 'Barabati Fort' 'Hirakud Dam' 'Chilika Lake' 'Tara Tarini Temple'
 'Badaghagara Waterfall' 'Chandipur Beach' 'Sanaghagara Waterfall'
 'Marina Beach' 'Meenakshi Amman Temple' 'Ramanathaswamy Temple'
 'Vivekananda Rock Memorial' 'Ooty Lake' 'Marudamalai Temple'
 'Kodaikanal Lake' 'Brihadeeswarar Temple' 'Shore Temple' 'Yercaud Lake'
 'Nellaiappar Temple' 'Nataraja Temple' 'Kanaka Durga Temple'
 'Rishikonda Beach' 'Mallikarjuna Swamy Temple' 'Papikondalu' 'Lepakshi'
 'Belum Caves' 'Amaravathi Temple' 'Uppalapadu Bird Sanctuary'
 'Gandikota Fort' 'Prasanthi Nilayam' 'Simhachalam Temple' 'Kailasagiri'
 'Submarine Museum' 'Borra Caves' 'War Memorial'
 'Indira Gandhi Zoological Park' 'Matsyadarshini Aquarium'
 'Visakha Museum' 'Nathula Pass' 'Pemayangtse Monastery' 'Char Dham'
 'Rumtek Monastery' 'Buddha Park' 'Baba Harbhajan Singh Temple'
 'Tsomgo Lake' 'Kamakhya Temple' 'Kaziranga National Park'
 'Umananda Island' 'Sivasagar Sivadol' 'Majuli Island'
 'Manas National Park' 'Hayagriva Madhava Temple'
 'Pobitora Wildlife Sanctuary' 'Tawang Monastery' 'Ujjayanta Palace'
 'Dumboor Lake' 'Unakoti Rock Carvings' 'Chitrakote Falls' 'Dz√ºkou Valley'
 'Promenade Beach' 'Auroville' 'Paradise Beach' 'Cellular Jail'
 'Radhanagar Beach' 'Bharatpur Beach' 'Limestone Caves' 'Naida Caves'
 'Diu Fort' 'Baba Baidyanath Temple' 'Pahari Mandir' 'Mahabodhi Temple'
 'Sanjay Gandhi Biological Park' 'Takhat Shri Harimandir Ji Patna Sahib'
 'Budhha Smriti Park' 'Kingdom of Dreams' 'Ambience Mall' 'DLF CyberHub'
 'Gurudwara Bangla Sahib' 'Kedarnath' 'DLF Mall of India'
 'The Grand Venice Mall' 'Nandankanan Zoological Park' 'Orion Mall'
 'Inorbit Mall Cyberabad' 'Jama Masjid' 'Buddh International Circuit'
 'Phoenix Palassio' 'LuLu International Shopping Mall' 'Rail Museum'
 'Living Root Bridge' 'Akshardham' 'Agra Fort'
 'Madhya Pradesh Tribal Museum' 'Albert Hall Museum' 'Name']

--------------------------------------------------

Unique values in column 'Type':
['War Memorial' 'Tomb' 'Temple' 'Theme Park' 'Observatory' 'Market' 'Fort'
 'Stepwell' 'Park' 'Museum' 'Zoo' 'Monument' 'Science' 'Promenade'
 'National Park' 'Religious Shrine' 'Beach' 'Amusement Park' 'Palace'
 'Botanical Garden' 'Government Building' 'Landmark' 'Lake' 'Film Studio'
 'Tombs' 'Bridge' 'Cricket Ground' 'Site' 'Church' 'Waterfall'
 'Bird Sanctuary' 'Historical' 'Cultural' 'Urban Development Project'
 'Wildlife Sanctuary' 'Shrine' 'Religious Site' 'Memorial'
 'Border Crossing' 'Sculpture Garden' 'Scenic Area' 'Viewpoint'
 'Mountain Peak' 'Cave' 'Mausoleum' 'Vineyard' 'Valley' 'Temples'
 'Prehistoric Site' 'Scenic Point' 'Monastery' 'Tea Plantation'
 'Adventure Sport' 'Trekking' 'Gurudwara' 'Ski Resort' 'Suspension Bridge'
 'Ghat' 'Orchard' 'Confluence' 'Hill' 'Gravity Hill' 'Village'
 'Sunrise Point' 'Dam' 'Spiritual Center' 'Aquarium' 'Religious Complex'
 'Island' 'River Island' 'Rock Carvings' 'Township' 'Natural Feature'
 'Entertainment' 'Mall' 'Commercial Complex' 'Mosque' 'Race Track' 'Type']

--------------------------------------------------

Unique values in column 'Establishment Year':
['1921' '1572' '2005' '2019' '1724' '1700' '1986' '1648' '1400' '1600'
 '2003' '1500' '1954' '1959' '1192' '1992' 'Unknown' '1924' '1922' '1996'
 '1881' '1831' '1431' '1987' '2013' '1878' '1760' '1870' '1956' '1997'
 '1591' '1563' '1951' '1976' '1800' '1963' '1994' '1943' '1814' '1855'
 '1809' '1864' '1876' '1898' '1835' '1605' '1612' '1617' '1640' '1988'
 '1915' '-400' '1965' '1950' '1890' '2018' '2012' '1451' '2002' '1799'
 '1559' '1156' '1980' '1236' '1459' '700' '1100' '1589' '1592' '1726'
 '1362' '1604' '1503' '1982' '1972' '1650' '1505' '2009' '2016' '1912'
 '600' '1900' '1656' '1974' '1121' '1732' '200' '1999' '2001' '1828'
 '-850' '-300' '1747' '900' '-3500' '1955' '1968' '1958' '1200' '1984'
 '400' '1975' '1939' '1990' '-820' '1868' '1936' '1751' '751' '1632'
 '1784' '1613' '-500' '1571' '1524' '1971' '1430' '24' '1351' '1981'
 '1941' '1837' '1949' '1887' '12th century' '1250' '11th century' '-987'
 '1957' 'Ancient' '6th century AD' '1970' '1824' '1863' '110'
 '7th century' '10th century' '14th century' '16th century' '198' '22'
 '1977' '1991' '1705' '211' '1960s' '213' '1967' '1905' '1734' '1680'
 '1901' '1906' '1535' '-260' '2010' '1960' '2004' '2011' '2020' '1565'
 '1727' 'Establishment Year']

--------------------------------------------------

Unique values in column 'time needed to visit in hrs':
['0.5' '2.0' '5.0' '3.0' '1.0' '4.0' '1.5' '2.5' '7.0' '5.5' '6.0'
 'time needed to visit in hrs']

--------------------------------------------------

Unique values in column 'Google review rating':
['4.6' '4.5' '4.1' '4.2' '4.4' '4.3' '4.8' '4.7' '1.4' '3.9' '4.9' '3.8'
 '4.0' '3.7' 'Google review rating']

--------------------------------------------------

Unique values in column 'Entrance Fee in INR':
['0' '30' '60' '50' '15' '35' '20' '80' '70' '500' '1149' '550' '25'
 '1150' '2500' '10' '3500' '200' '7500' '350' '300' '100' '40' '750' '75'
 '150' '1500' '5' '250' '65' '650' '1100' '890' 'Entrance Fee in INR']

--------------------------------------------------

Unique values in column 'Airport with 50km Radius':
['Yes' 'No' 'Airport with 50km Radius']

--------------------------------------------------

Unique values in column 'Weekly Off':
[nan 'Monday' 'Sunday' 'Friday' 'Yes' 'Tuesday' 'Weekly Off']

--------------------------------------------------

Unique values in column 'Significance':
['Historical' 'Religious' 'Environmental' 'Scientific' 'Market'
 'Botanical' 'Artistic' 'Scenic' 'Wildlife' 'Recreational' 'Nature'
 'Architectural' 'Entertainment' 'Sports' 'Educational' 'Cultural' 'Food'
 'Spiritual' 'Archaeological' 'Adventure' 'Agricultural'
 'Engineering Marvel' 'Natural Wonder' 'Trekking' 'Shopping'
 'Significance']

--------------------------------------------------

Unique values in column 'DSLR Allowed':
['Yes' 'No' 'DSLR Allowed']

--------------------------------------------------

Unique values in column 'Number of google review in lakhs':
['2.6' '0.4' '0.27' '0.31' '0.25' '0.59' '1.5' '0.41' '0.16' '0.23' '0.48'
 '0.08' '1.37' '3.6' '0.34' '0.6' '1.05' '0.33' '0.05' '0.35' '0.95' '0.9'
 '1.32' '0.8' '1.14' '2.1' '1.2' '0.5' '0.45' '0.67' '0.2' '0.86' '0.73'
 '0.18' '0.82' '0.1' '0.66' '0.88' '0.47' '0.26' '0.3' '0.19' '0.01'
 '0.03' '0.12' '0.17' '0.39' '0.49' '0.11' '1.3' '0.51' '0.56' '0.09'
 '1.6' '0.64' '1.9' '0.32' '0.46' '0.059' '2.2' '0.14' '0.22' '0.68' '2.5'
 '0.15' '0.21' '0.69' '0.065' '0.02' '0.63' '0.07' '0.025' '0.015' '1.1'
 '0.55' '0.29' '0.035' '2.25' '0.13' '0.37' '0.0165' '0.045' '0.011'
 '0.012' '1.0' '0.83' '0.018' '0.014' '0.055' '0.65' '0.61' '0.019' '0.28'
 '0.44' '0.032' '0.075' '0.041' '0.7' '0.068' '0.037' '0.04' '1.8' '0.71'
 '2.0' '0.81' '7.4' '0.24' '0.06' 'Number of google review in lakhs']

--------------------------------------------------

Unique values in column 'Best Time to visit':
['Evening' 'Afternoon' 'Morning' 'All' 'All ' 'Anytime' 'Night'
 'Best Time to visit']

--------------------------------------------------

In [15]:
df.shape

(651, 16)

In [13]:
df.head(100)

,Unnamed: 0,Zone,State,City,Name,Type,Establishment Year,time needed to visit in hrs,Google review rating,Entrance Fee in INR,Airport with 50km Radius,Weekly Off,Significance,DSLR Allowed,Number of google review in lakhs,Best Time to visit
0,0.0,Northern,Delhi,Delhi,India Gate,War Memorial,1921,0.5,4.6,0,Yes,NaN,Historical,Yes,2.6,Evening
1,1.0,Northern,Delhi,Delhi,Humayun's Tomb,Tomb,1572,2.0,4.5,30,Yes,NaN,Historical,Yes,0.4,Afternoon
2,2.0,Northern,Delhi,Delhi,Akshardham Temple,Temple,2005,5.0,4.6,60,Yes,NaN,Religious,No,0.4,Afternoon
3,3.0,Northern,Delhi,Delhi,Waste to Wonder Park,Theme Park,2019,2.0,4.1,50,Yes,Monday,Environmental,Yes,0.27,Evening
4,4.0,Northern,Delhi,Delhi,Jantar Mantar,Observatory,1724,2.0,4.2,15,Yes,NaN,Scientific,Yes,0.31,Morning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95.0,Northern,Punjab,Chandigarh,Rock Garden,Sculpture Garden,1976,2.0,4.5,30,Yes,NaN,Artistic,Yes,0.5,All
96,96.0,Southern,Kerala,Alappuzha,Alappuzha Beach,Beach,Unknown,1.5,4.5,0,Yes,NaN,Recreational,Yes,0.11,All
97,97.0,Southern,Kerala,Munnar,Munnar Tea Gardens,Scenic Area,Unknown,2.0,4.3,0,No,NaN,Nature,Yes,0.3,All
98,98.0,Southern,Kerala,Kochi,Fort Kochi,Site,1503,1.0,4.4,0,Yes,NaN,Historical,Yes,0.1,All
99,99.0,Southern,Kerala,Thiruvananthapuram,Padmanabhaswamy Temple,Temple,Unknown,1.0,4.7,0,Yes,NaN,Religious,No,0.46,All

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 651 entries, 0 to 650
Data columns (total 16 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        650 non-null    float64
 1   Zone                              651 non-null    object
 2   State                             651 non-null    object
 3   City                              651 non-null    object
 4   Name                              651 non-null    object
 5   Type                              651 non-null    object
 6   Establishment Year                651 non-null    object
 7   time needed to visit in hrs       651 non-null    object
 8   Google review rating              651 non-null    object
 9   Entrance Fee in INR               651 non-null    object
 10  Airport with 50km Radius          651 non-null    object
 11  Weekly Off                        65 non-null     object
 12  Significance                      651 non-null    object
 13  DSLR Allowed                      651 non-null    object
 14  Number of google review in lakhs  651 non-null    object
 15  Best Time to visit                651 non-null    object
dtypes: float64(1), object(15)
memory usage: 81.5+ KB

In [63]:
df.drop_duplicates(inplace=True)

In [64]:
data = df.drop(["Name","Unnamed: 0","Establishment Year","Best Time to visit","Number of google review in lakhs","DSLR Allowed","Google review rating","Weekly Off","Type","City","State","time needed to visit in hrs","Entrance Fee in INR"],axis =1)

In [65]:
categorical_cols = ['Zone', 'Significance']  # and others if needed
df[categorical_cols] = df[categorical_cols].fillna('Unknown').astype(str)

In [66]:
# Step 1: Get the transformed data
transformed_data = preprocessor.fit_transform(df)

# Step 2: Get one-hot encoded feature names
onehot_feature_names = preprocessor.named_transformers_["onehot"].get_feature_names_out(categorical_cols)

# Step 3: Get remaining column names (non-categorical)
non_categorical_cols = [col for col in df.columns if col not in categorical_cols]

# Step 4: Combine all column names
output_columns = list(onehot_feature_names) + non_categorical_cols

# Step 5: Create the final DataFrame
pca_data = pd.DataFrame(transformed_data, columns=output_columns)

In [67]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 326 entries, 0 to 325
Data columns (total 3 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Zone                      326 non-null    object
 1   Airport with 50km Radius  326 non-null    object
 2   Significance              326 non-null    object
dtypes: object(3)
memory usage: 10.2+ KB

In [68]:
from sklearn.preprocessing import LabelEncoder

# Make sure the column is treated as string
data["Airport with 50km Radius"] = data["Airport with 50km Radius"].astype(str)

# Initialize and fit LabelEncoder
le_airport = LabelEncoder()
data["Airport with 50km Radius"] = le_airport.fit_transform(data["Airport with 50km Radius"])

In [69]:
data

         Zone  Airport with 50km Radius   Significance
0    Northern                         2     Historical
1    Northern                         2     Historical
2    Northern                         2      Religious
3    Northern                         2  Environmental
4    Northern                         2     Scientific
..        ...                       ...            ...
321   Central                         2     Historical
322   Central                         2       Cultural
323  Northern                         2     Historical
324  Northern                         2     Historical
325      Zone                         0   Significance

[326 rows x 3 columns]

In [70]:
df[["Zone", "Type", "Significance", "State", "City"]].nunique()

Zone              7
Type             79
Significance     26
State            34
City            215
dtype: int64

In [71]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 326 entries, 0 to 325
Data columns (total 3 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Zone                      326 non-null    object
 1   Airport with 50km Radius  326 non-null    int32
 2   Significance              326 non-null    object
dtypes: int32(1), object(2)
memory usage: 8.9+ KB

In [72]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Define categorical columns
categorical_cols = ["Zone", "Significance"]

# Clean the data
data[categorical_cols] = data[categorical_cols].fillna("Unknown").astype(str)

# Create the OneHotEncoder
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Build ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ("onehot", encoder, categorical_cols)
    ],
    remainder="passthrough"
)

# Fit and transform
encoded_features = preprocessor.fit_transform(data)

# ‚úÖ Get all output column names (including one-hot and passthrough)
feature_names = preprocessor.get_feature_names_out()

# Convert to DataFrame
encoded_df = pd.DataFrame(encoded_features, columns=feature_names)

# Preview the result
print(encoded_df.head())

   onehot__Zone_Central  onehot__Zone_Eastern  onehot__Zone_North Eastern  \
0                   0.0                   0.0                         0.0
1                   0.0                   0.0                         0.0
2                   0.0                   0.0                         0.0
3                   0.0                   0.0                         0.0
4                   0.0                   0.0                         0.0

   onehot__Zone_Northern  onehot__Zone_Southern  onehot__Zone_Western  \
0                    1.0                    0.0                   0.0
1                    1.0                    0.0                   0.0
2                    1.0                    0.0                   0.0
3                    1.0                    0.0                   0.0
4                    1.0                    0.0                   0.0

   onehot__Zone_Zone  onehot__Significance_Adventure  \
0                0.0                             0.0
1                0.0                             0.0
2                0.0                             0.0
3                0.0                             0.0
4                0.0                             0.0

   onehot__Significance_Agricultural  onehot__Significance_Archaeological  \
0                                0.0                                  0.0
1                                0.0                                  0.0
2                                0.0                                  0.0
3                                0.0                                  0.0
4                                0.0                                  0.0

   ...  onehot__Significance_Religious  onehot__Significance_Scenic  \
0  ...                             0.0                          0.0
1  ...                             0.0                          0.0
2  ...                             1.0                          0.0
3  ...                             0.0                          0.0
4  ...                             0.0                          0.0

   onehot__Significance_Scientific  onehot__Significance_Shopping  \
0                              0.0                            0.0
1                              0.0                            0.0
2                              0.0                            0.0
3                              0.0                            0.0
4                              1.0                            0.0

   onehot__Significance_Significance  onehot__Significance_Spiritual  \
0                                0.0                             0.0
1                                0.0                             0.0
2                                0.0                             0.0
3                                0.0                             0.0
4                                0.0                             0.0

   onehot__Significance_Sports  onehot__Significance_Trekking  \
0                          0.0                            0.0
1                          0.0                            0.0
2                          0.0                            0.0
3                          0.0                            0.0
4                          0.0                            0.0

   onehot__Significance_Wildlife  remainder__Airport with 50km Radius
0                            0.0                                  2.0
1                            0.0                                  2.0
2                            0.0                                  2.0
3                            0.0                                  2.0
4                            0.0                                  2.0

[5 rows x 34 columns]

In [73]:
encoded_df

,onehot__Zone_Central,onehot__Zone_Eastern,onehot__Zone_North Eastern,onehot__Zone_Northern,onehot__Zone_Southern,onehot__Zone_Western,onehot__Zone_Zone,onehot__Significance_Adventure,onehot__Significance_Agricultural,onehot__Significance_Archaeological,...,onehot__Significance_Religious,onehot__Significance_Scenic,onehot__Significance_Scientific,onehot__Significance_Shopping,onehot__Significance_Significance,onehot__Significance_Spiritual,onehot__Significance_Sports,onehot__Significance_Trekking,onehot__Significance_Wildlife,remainder__Airport with 50km Radius
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
322,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
323,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
324,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
325,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [74]:
encoded_features = pd.DataFrame(encoded_features)

In [75]:
encoded_df.head()

,onehot__Zone_Central,onehot__Zone_Eastern,onehot__Zone_North Eastern,onehot__Zone_Northern,onehot__Zone_Southern,onehot__Zone_Western,onehot__Zone_Zone,onehot__Significance_Adventure,onehot__Significance_Agricultural,onehot__Significance_Archaeological,...,onehot__Significance_Religious,onehot__Significance_Scenic,onehot__Significance_Scientific,onehot__Significance_Shopping,onehot__Significance_Significance,onehot__Significance_Spiritual,onehot__Significance_Sports,onehot__Significance_Trekking,onehot__Significance_Wildlife,remainder__Airport with 50km Radius
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0

In [76]:
encoded_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326 entries, 0 to 325
Data columns (total 34 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   onehot__Zone_Central                     326 non-null    float64
 1   onehot__Zone_Eastern                     326 non-null    float64
 2   onehot__Zone_North Eastern               326 non-null    float64
 3   onehot__Zone_Northern                    326 non-null    float64
 4   onehot__Zone_Southern                    326 non-null    float64
 5   onehot__Zone_Western                     326 non-null    float64
 6   onehot__Zone_Zone                        326 non-null    float64
 7   onehot__Significance_Adventure           326 non-null    float64
 8   onehot__Significance_Agricultural        326 non-null    float64
 9   onehot__Significance_Archaeological      326 non-null    float64
 10  onehot__Significance_Architectural       326 non-null    float64
 11  onehot__Significance_Artistic            326 non-null    float64
 12  onehot__Significance_Botanical           326 non-null    float64
 13  onehot__Significance_Cultural            326 non-null    float64
 14  onehot__Significance_Educational         326 non-null    float64
 15  onehot__Significance_Engineering Marvel  326 non-null    float64
 16  onehot__Significance_Entertainment       326 non-null    float64
 17  onehot__Significance_Environmental       326 non-null    float64
 18  onehot__Significance_Food                326 non-null    float64
 19  onehot__Significance_Historical          326 non-null    float64
 20  onehot__Significance_Market              326 non-null    float64
 21  onehot__Significance_Natural Wonder      326 non-null    float64
 22  onehot__Significance_Nature              326 non-null    float64
 23  onehot__Significance_Recreational        326 non-null    float64
 24  onehot__Significance_Religious           326 non-null    float64
 25  onehot__Significance_Scenic              326 non-null    float64
 26  onehot__Significance_Scientific          326 non-null    float64
 27  onehot__Significance_Shopping            326 non-null    float64
 28  onehot__Significance_Significance        326 non-null    float64
 29  onehot__Significance_Spiritual           326 non-null    float64
 30  onehot__Significance_Sports              326 non-null    float64
 31  onehot__Significance_Trekking            326 non-null    float64
 32  onehot__Significance_Wildlife            326 non-null    float64
 33  remainder__Airport with 50km Radius      326 non-null    float64
dtypes: float64(34)
memory usage: 86.7 KB

In [82]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.neighbors import NearestNeighbors

# Assuming pca_data already exists
# Step 1: Select numeric columns only
numeric_cols = pca_data.select_dtypes(include=['int64', 'float64']).columns
X = pca_data[numeric_cols]

# Step 2: Scale the numeric features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 3: Apply PCA to reduce to 2 components
pca = PCA(n_components=2)
pca_result = pca.fit_transform(X_scaled)

# Step 4: Create a DataFrame with PCA results
pca_df = pd.DataFrame(pca_result, columns=["PC1", "PC2"])

# Step 5: Fit KNN on PCA results
knn_model = NearestNeighbors(n_neighbors=5, metric='euclidean')
knn_model.fit(pca_df)

# Step 6: Query similar destinations to the first one
distances, indices = knn_model.kneighbors([pca_df.iloc[0]])

# Step 7: Display results
print("üîç Input destination:")
print(pca_data.iloc[0][['remainder__Name', 'remainder__City', 'remainder__State']])

print("\n‚ú® Top 5 similar destinations:")
print(pca_data.iloc[indices[0]][['remainder__Name', 'remainder__City', 'remainder__State']])

ValueError: at least one array or dtype is required

In [78]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Load the data (if not already)
data = pd.read_csv("final.csv")

# Drop unwanted columns
if "Unnamed: 0" in data.columns:
    data = data.drop(columns=["Unnamed: 0"])

# Define categorical columns to encode
categorical_cols = ["Zone", "Significance"]

# Fill missing values and ensure they're strings
data[categorical_cols] = data[categorical_cols].fillna("Unknown").astype(str)

# Create OneHotEncoder
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Build ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ("onehot", encoder, categorical_cols)
    ],
    remainder="passthrough"  # Keep all other columns as is
)

# Fit and transform the data
encoded_features = preprocessor.fit_transform(data)

# Get new feature names
encoded_feature_names = preprocessor.get_feature_names_out()

# Convert back to DataFrame
encoded_df = pd.DataFrame(encoded_features, columns=encoded_feature_names)

# Optional: reset index if needed
encoded_df.index = data.index  # Match index to original DataFrame

# Preview the final DataFrame
print(encoded_df.head())

  onehot__Zone_Central onehot__Zone_Eastern onehot__Zone_North Eastern  \
0                  0.0                  0.0                        0.0
1                  0.0                  0.0                        0.0
2                  0.0                  0.0                        0.0
3                  0.0                  0.0                        0.0
4                  0.0                  0.0                        0.0

  onehot__Zone_Northern onehot__Zone_Southern onehot__Zone_Western  \
0                   1.0                   0.0                  0.0
1                   1.0                   0.0                  0.0
2                   1.0                   0.0                  0.0
3                   1.0                   0.0                  0.0
4                   1.0                   0.0                  0.0

  onehot__Zone_Zone onehot__Significance_Adventure  \
0               0.0                            0.0
1               0.0                            0.0
2               0.0                            0.0
3               0.0                            0.0
4               0.0                            0.0

  onehot__Significance_Agricultural onehot__Significance_Archaeological  ...  \
0                               0.0                                 0.0  ...
1                               0.0                                 0.0  ...
2                               0.0                                 0.0  ...
3                               0.0                                 0.0  ...
4                               0.0                                 0.0  ...

  remainder__Type remainder__Establishment Year  \
0    War Memorial                          1921
1            Tomb                          1572
2          Temple                          2005
3      Theme Park                          2019
4     Observatory                          1724

  remainder__time needed to visit in hrs remainder__Google review rating  \
0                                    0.5                             4.6
1                                    2.0                             4.5
2                                    5.0                             4.6
3                                    2.0                             4.1
4                                    2.0                             4.2

  remainder__Entrance Fee in INR remainder__Airport with 50km Radius  \
0                              0                                 Yes
1                             30                                 Yes
2                             60                                 Yes
3                             50                                 Yes
4                             15                                 Yes

  remainder__Weekly Off remainder__DSLR Allowed  \
0                   NaN                     Yes
1                   NaN                     Yes
2                   NaN                      No
3                Monday                     Yes
4                   NaN                     Yes

  remainder__Number of google review in lakhs remainder__Best Time to visit
0                                         2.6                       Evening
1                                         0.4                     Afternoon
2                                         0.4                     Afternoon
3                                        0.27                       Evening
4                                        0.31                       Morning

[5 rows x 46 columns]

In [79]:
#  2. Map Visualization

In [25]:
import joblib

# Save the model
joblib.dump(knn_model, 'knn_model.pkl')

# If you also want to save the preprocessor
joblib.dump(preprocessor, 'preprocessor.pkl')

['preprocessor.pkl']

In [26]:
pca_data =encoded_df.copy()

In [40]:
print(pca_data.columns.tolist())

['onehot__Zone_Central', 'onehot__Zone_Eastern', 'onehot__Zone_North Eastern', 'onehot__Zone_Northern', 'onehot__Zone_Southern', 'onehot__Zone_Western', 'onehot__Zone_Zone', 'onehot__Significance_Adventure', 'onehot__Significance_Agricultural', 'onehot__Significance_Archaeological', 'onehot__Significance_Architectural', 'onehot__Significance_Artistic', 'onehot__Significance_Botanical', 'onehot__Significance_Cultural', 'onehot__Significance_Educational', 'onehot__Significance_Engineering Marvel', 'onehot__Significance_Entertainment', 'onehot__Significance_Environmental', 'onehot__Significance_Food', 'onehot__Significance_Historical', 'onehot__Significance_Market', 'onehot__Significance_Natural Wonder', 'onehot__Significance_Nature', 'onehot__Significance_Recreational', 'onehot__Significance_Religious', 'onehot__Significance_Scenic', 'onehot__Significance_Scientific', 'onehot__Significance_Shopping', 'onehot__Significance_Significance', 'onehot__Significance_Spiritual', 'onehot__Significance_Sports', 'onehot__Significance_Trekking', 'onehot__Significance_Wildlife', 'remainder__State', 'remainder__City', 'remainder__Name', 'remainder__Type', 'remainder__Establishment Year', 'remainder__time needed to visit in hrs', 'remainder__Google review rating', 'remainder__Entrance Fee in INR', 'remainder__Airport with 50km Radius', 'remainder__Weekly Off', 'remainder__DSLR Allowed', 'remainder__Number of google review in lakhs', 'remainder__Best Time to visit']

In [33]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.decomposition import PCA

In [38]:
pca_data.columns = pca_data.columns.str.strip()

In [39]:
categorical_cols = ['Zone', 'Significance']
pca_data[categorical_cols] = pca_data[categorical_cols].fillna('Unknown').astype(str)

KeyError: "None of [Index(['Zone', 'Significance'], dtype='object')] are in the [columns]"

In [32]:
categorical_cols = ['Zone', 'Significance']

In [34]:
remainder_cols = [
    'State', 'City', 'Name', 'Type', 'Establishment Year',
    'time needed to visit in hrs', 'Google review rating', 'Entrance Fee in INR',
    'Airport with 50km Radius', 'Weekly Off', 'DSLR Allowed',
    'Number of google review in lakhs', 'Best Time to visit'
]

In [35]:
print(set(remainder_cols) - set(pca_data.columns))

{'DSLR Allowed', 'time needed to visit in hrs', 'Google review rating', 'Establishment Year', 'Name', 'Airport with 50km Radius', 'Weekly Off', 'Number of google review in lakhs', 'State', 'Entrance Fee in INR', 'Type', 'City', 'Best Time to visit'}

In [36]:
# Fill NAs in categorical columns
pca_data[categorical_cols] = pca_data[categorical_cols].fillna('Unknown').astype(str)

KeyError: "None of [Index(['Zone', 'Significance'], dtype='object')] are in the [columns]"

In [28]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Define categorical columns (update as needed)
categorical_cols = ["Zone", "Significance", "City", "State", "Type", "Name", "Weekly Off", "DSLR Allowed", "Best Time to visit"]

# Fill missing values
pca_data[categorical_cols] = pca_data[categorical_cols].fillna("Unknown").astype(str)

# Build preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), categorical_cols)
    ],
    remainder="passthrough"
)

# Encode full data
encoded_data = preprocessor.fit_transform(pca_data)

# Now scale the encoded numeric + one-hot data
scaler = StandardScaler()
scaled_data = scaler.fit_transform(encoded_data)

KeyError: "None of [Index(['Zone', 'Significance', 'City', 'State', 'Type', 'Name', 'Weekly Off',\n       'DSLR Allowed', 'Best Time to visit'],\n      dtype='object')] are in the [columns]"

In [36]:
user_encoded

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 1.]])